name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint, format and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Initialize submodules
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Format
        run: deno fmt --check
      - name: Test
        run: deno test
